### ISSUE TITLE
Add NISAR s3credential endpoint support

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-api-nasa#115] opened 2024-05-16 20:38 UTC
To use the NISAR simulated data we need to access it from a special endpoint at ASF DAAC that's different than the normal one (which works for S1 data).

The credential endpoint is:
`https://nisar.asf.earthdatacloud.nasa.gov/s3credentials`
https://github.com/nsidc/earthaccess/discussions/482#discussioncomment-8832681

The data bucket is:
`s3://sds-n-cumulus-prod-nisar-sample-data/`

An example file to obtain:
`s3://sds-n-cumulus-prod-nisar-sample-data/GCOV/ALOS1_Rosamond_20081012/NISAR_L2_PR_GCOV_001_005_A_219_4020_SHNA_A_20081012T060910_20081012T060926_P01101_F_N_J_001.h5`

Code to test credential endpoint:
```
from maap.maap import MAAP
maap = MAAP()

def get_s3_creds(url):
    return maap.aws.earthdata_s3_credentials(url)

def get_s3_client(s3_cred_endpoint):
    creds=get_s3_creds(s3_cred_endpoint)
    boto3_session = boto3.Session(
            aws_access_key_id=creds['accessKeyId'],
            aws_secret_access_key=creds['secretAccessKey'],
            aws_session_token=creds['sessionToken']
    )
    return boto3_session.client("s3")

asf_s3 = "https://nisar.asf.earthdatacloud.nasa.gov/s3credentials"
creds = get_s3_creds(asf_s3)
```
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[12], line 2
      1 asf_s3 = "https://nisar.asf.earthdatacloud.nasa.gov/s3credentials"
----> 2 creds = get_s3_creds(asf_s3)

Cell In[11], line 2, in get_s3_creds(url)
      1 def get_s3_creds(url):
----> 2     return maap.aws.earthdata_s3_credentials(url)

File /maap-py/maap/AWS.py:62, in AWS.earthdata_s3_credentials(self, endpoint_uri)
     57 _url = self._earthdata_s3_credentials_endpoint.replace(
     58     "{endpoint_uri}", _parsed_endpoint
     59 )
     61 response = requests.get(url=_url, headers=self._api_header)
---> 62 response.raise_for_status()
     64 result = json.loads(response.text)
     65 result["DAAC"] = urllib.parse.urlparse(endpoint_uri).netloc

File /opt/conda/envs/vanilla/lib/python3.10/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1016     http_error_msg = (
   1017         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1018     )
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.maap-project.org/api/members/self/awsAccess/edcCredentials/https%253A%252F%252Fnisar.asf.earthdatacloud.nasa.gov%252Fs3credentials
```

cc: @smk0033 as part of https://github.com/MAAP-Project/maap-documentation/pull/401

**Comment by smk0033** [comment] 2024-06-05 19:43
@bsatoriu Hi Brian, just wanted to check in and see if there were any updates on this issue yet?

**Comment by bsatoriu** [comment] 2024-06-11 22:32
@wildintellect @smk0033 the NISAR EDL application admin needs to check the 'Enable EDL compatibility option'. I created a [related PR](https://github.com/MAAP-Project/maap-api-nasa/pull/120) that bubbles of the incompatibility error from maap-py.

Once this EDL setting has been updated on the NISAR side, the following will return valid s3 credentials: `maap.aws.earthdata_s3_credentials('https://nisar.asf.earthdatacloud.nasa.gov/s3credentials')`

**Comment by wildintellect** [comment] 2024-06-11 22:38
@bsatoriu any idea who we should contact? maybe Joe Kennedy at ASF?

**Comment by bsatoriu** [comment] 2024-06-11 22:47
@wildintellect yes and Doug Ellison might know of a good contact if Joe doesn't know.

**Comment by jhkennedy** [comment] 2024-06-12 00:11
I'll pass this along to our I&A team, who manage that endpoint.

**Comment by wildintellect** [comment] 2024-06-12 00:11
I pinged @jhkennedy in Slack, he's going to forward the message on to the correct team.

**Comment by jhkennedy** [comment] 2024-06-12 19:52
Unfortunately, the NISAR mission has chosen to host restricted project files behind the NISAR endpoint, which is not compliant with EDL policy, so we cannot, at this time, check the "Enable EDL compatibility" option. We're exploring an alternative method with the NISAR mission team so that we can be compliant with EDL policy, but I don't have a timeline for doing so.

@bsatoriu I'm not sure why MAAP actually cares about this. Can you explain why this is a requirement? As far as I'm aware, this just means that we don't fail open, that clients would only notice when EDL is in a failure state, and there's no way for clients to inspect this value. I don't see anything in the code from the various linked issues/PRs that would cause a 500 error to always be thrown, and I would only expect to see that if EDL is in a failed state.

Notably, I can get the credentials just fine with requests or using Earthacess:
```python
>>> import earthaccess
>>>
>>> earthaccess.__store__.auth.get_s3_credentials(endpoint='https://nisar.asf.earthdatacloud.nasa.gov/s3credentials')
{'accessKeyId': 'XXX',
 'secretAccessKey': 'XXX',
 'sessionToken': 'XXX',
 'expiration': '2024-06-12 20:48:21+00:00'}
````

**Comment by bsatoriu** [comment] 2024-06-13 15:15
@jhkennedy MAAP cares about EDL compatibility because we doesn't store EDL credentials--we use a single sign on service and keep a secured EDL user token for accessing DAAC data on behalf of MAAP algorithm developers. 

EDL compatibility allows EDL-registered applications like MAAP to use tokens for accessing DAAC data (some of the docs I used previously were moved but I found this: https://opendap.github.io/documentation/tutorials/ClientAuthenticationWithEDLTokens.html#_overview). So, this is an important requirement for MAAP to be able to register algorithms and execute those algorithms securely in headless environments.

The error "Client is not EDL policy compatible" is being generated from the NISAR endpoint `https://nisar.asf.earthdatacloud.nasa.gov/s3credentials` when sending a request with the required headers: https://github.com/MAAP-Project/maap-api-nasa/blob/develop/api/cas/cas_auth.py#L288

**Comment by bsatoriu** [comment] 2024-06-13 19:23
One additional note: I'm not finding much documentation on EDL "federated" tokens that we relied on initially when developing the EDL auth features in MAAP. The guidance we used at the time required an EDL application token in addition to the user's token when requesting protected resources. See: https://github.com/MAAP-Project/maap-api-nasa/blob/develop/api/cas/cas_auth.py#L288C68-L288C100. 

When I remove this particular segment of code, the "Client is not EDL policy compatible" message is omitted from the HTTP response, so it appears this additional token is still needed.

**Comment by jhkennedy** [comment] 2024-06-13 19:27
@bsatoriu, thanks for the follow-up! I've brought this to the attention of the DAAC and NISAR project managers here, as well as the I&A team; we'll dig into this. Do you have a need-by time? Or is it "yesterday" like most things? ha!

**Comment by bsatoriu** [comment] 2024-06-13 19:41
@jhkennedy thanks so much for your help. I think @smk0033 needed it "yesterday" as it is a blocker at the moment -- not sure of the urgency level.

**Comment by smk0033** [comment] 2024-06-13 19:45
Thank you both! The sooner the better if possible, we were hoping to close a ticket out by the end of next week if we can. @bsatoriu @jhkennedy

**Comment by wildintellect** [comment] 2024-06-13 20:50
@jhkennedy it's not a blocker overall, since we know how get to the data using direct credentials instead of federated. It is a longer term concern if the official NISAR distribution won't have this feature since we're relying on it for compatibility with MAAP. So nice to have by July, pretty important before Sept.

**Comment by mattp0** [comment] 2024-06-17 20:02
👋🏼  folks, just want to chime in from the ASF I&A team. 

I am one of the admins for the NISAR EDL application. Because during mission we will be serving restricted data to support the mission, we can not hit the compatibility checkbox at this time. Our team is working with the EDL team for recommendations and discussing what options we have.

**Comment by mattp0** [comment] 2024-06-18 20:29
ESDIS moved quick on this, we have been given the green light on this and I applied the configuration to the application. Please let me know if there is other issues.

**Comment by bsatoriu** [comment] 2024-06-20 15:51
I can confirm that the s3 credential endpoint is working from maap-py now. Thank you all!

**Comment by smk0033** [comment] 2024-06-24 18:51
Thanks, all! It's greatly appreciated!

**Comment by smk0033** [comment] 2024-06-26 18:24
Solved - closing this issue!

**Closed by smk0033** 2024-06-26 18:24 UTC
